//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RedeCegonha.Modelagem
{
    using System;
    using System.Collections.Generic;
    
    public partial class Crianca
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Crianca()
        {
            this.ExamesRecemNascido = new HashSet<ExamesRecemNascido>();
        }
    
        public int Id { get; set; }
        public int Declaracao { get; set; }
        public decimal Peso { get; set; }
        public string Sexo { get; set; }
        public int IdMae { get; set; }
        public int Apgar2 { get; set; }
        public int IdApgar1 { get; set; }
        public int Apgar5Id { get; set; }
    
        public virtual Mae Mae { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ExamesRecemNascido> ExamesRecemNascido { get; set; }
        public virtual Apgar5 Apgar5 { get; set; }
        public virtual Apgar1 Apgar1 { get; set; }
    }
}
