//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RedeCegonha.Modelagem
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExamesRecemNascido
    {
        public int Id { get; set; }
        public string TesteDoPesinho { get; set; }
        public string TipagemSanguinea { get; set; }
        public string TesteDaOrelhinha { get; set; }
        public string ReflexoVermelho { get; set; }
        public int IdCrianca { get; set; }
        public int IdMedico { get; set; }
    
        public virtual Crianca Crianca { get; set; }
        public virtual Medico Medico { get; set; }
    }
}
