//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RedeCegonha.Modelagem
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExamesMae
    {
        public int Id { get; set; }
        public string Glicemia { get; set; }
        public string SorologiaEpatiteB { get; set; }
        public string HIV { get; set; }
        public string UrinaTipo1 { get; set; }
        public int IdMae { get; set; }
        public int IdMedico { get; set; }
    
        public virtual Mae Mae { get; set; }
        public virtual Medico Medico { get; set; }
    }
}
