//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RedeCegonha.Modelagem
{
    using System;
    using System.Collections.Generic;
    
    public partial class Mae
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Mae()
        {
            this.Crianca = new HashSet<Crianca>();
            this.Parto = new HashSet<Parto>();
            this.ExamesMae = new HashSet<ExamesMae>();
            this.MaeConsultaPreNatal = new HashSet<MaeConsultaPreNatal>();
        }
    
        public int Id { get; set; }
        public string Nome { get; set; }
        public int Idade { get; set; }
        public int QuantFilhosVivos { get; set; }
        public int QuantFilhosMortos { get; set; }
        public string Escolaridade { get; set; }
        public string EstadoCivil { get; set; }
        public string Cpf { get; set; }
        public string Rua { get; set; }
        public string Cidade { get; set; }
        public string Telefone { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Crianca> Crianca { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Parto> Parto { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ExamesMae> ExamesMae { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MaeConsultaPreNatal> MaeConsultaPreNatal { get; set; }
    }
}
