//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RedeCegonha.Modelagem
{
    using System;
    using System.Collections.Generic;
    
    public partial class MaeConsultaPreNatal
    {
        public int Id { get; set; }
        public int IdMae { get; set; }
        public int IdConsultaPreNatal { get; set; }
        public int ConsultaPreNatalId { get; set; }
    
        public virtual ConsultaPreNatal ConsultaPreNatal { get; set; }
        public virtual Mae Mae { get; set; }
    }
}
