//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RedeCegonha.Modelagem
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ModelagemLaisContainer : DbContext
    {
        public ModelagemLaisContainer()
            : base("name=ModelagemLaisContainer")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Crianca> CriancaSet { get; set; }
        public virtual DbSet<Mae> MaeSet { get; set; }
        public virtual DbSet<Parto> PartoSet { get; set; }
        public virtual DbSet<MaeConsultaPreNatal> MaeConsultaPreNatalSet { get; set; }
        public virtual DbSet<Medico> MedicoSet { get; set; }
        public virtual DbSet<Apgar1> Apgar1Set { get; set; }
        public virtual DbSet<Apgar5> Apgar5Set { get; set; }
        public virtual DbSet<Usuario> UsuarioSet { get; set; }
        public virtual DbSet<ConsultaPreNatal> ConsultaPreNatalSet { get; set; }
        public virtual DbSet<ExamesRecemNascido> ExamesRecemNascidoSet { get; set; }
        public virtual DbSet<ExamesMae> ExamesMaeSet { get; set; }
    }
}
