// <auto-generated />
using laiscegonha.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;

namespace LaisCegonha.Migrations
{
    [DbContext(typeof(LaisContext))]
    [Migration("20180424123349_CreateDatabase")]
    partial class CreateDatabase
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("MySql:ValueGenerationStrategy", MySqlValueGenerationStrategy.IdentityColumn)
                .HasAnnotation("ProductVersion", "2.0.1-rtm-125");

            modelBuilder.Entity("laiscegonha.Models.ConsultaPreNatal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<decimal>("AlturaUterina");

                    b.Property<decimal>("BatimentoCadiacoFetal");

                    b.Property<DateTime>("DataConsulta");

                    b.Property<string>("Diabetes");

                    b.Property<string>("EstadoNutricional");

                    b.Property<string>("Fumante");

                    b.Property<string>("Gravidez");

                    b.Property<string>("HoraConsulta");

                    b.Property<string>("MovitacaoFetal");

                    b.Property<int>("NumeroDeConsultas");

                    b.Property<string>("Obsidade");

                    b.Property<decimal>("PressaoArterial");

                    b.Property<string>("TempoGestacao");

                    b.Property<string>("TipoParto");

                    b.Property<string>("UsuariaAlcool");

                    b.Property<string>("UsuariaDrogas");

                    b.HasKey("Id");

                    b.ToTable("Consultas");
                });

            modelBuilder.Entity("laiscegonha.Models.Crianca", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Apgar1");

                    b.Property<string>("Apgar5");

                    b.Property<int>("Declaracao");

                    b.Property<int>("IdMae");

                    b.Property<int?>("MaeId");

                    b.Property<decimal>("Peso");

                    b.Property<string>("Sexo");

                    b.HasKey("Id");

                    b.HasIndex("MaeId");

                    b.ToTable("Criancas");
                });

            modelBuilder.Entity("laiscegonha.Models.Mae", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Cidade");

                    b.Property<string>("Cpf");

                    b.Property<string>("Escolaridade");

                    b.Property<string>("EstadoCivil");

                    b.Property<int>("Idade");

                    b.Property<string>("Nome");

                    b.Property<int>("QuantFilhosMortos");

                    b.Property<int>("QuantFilhosVivos");

                    b.Property<string>("Rua");

                    b.Property<string>("Telefone");

                    b.HasKey("Id");

                    b.ToTable("Maes");
                });

            modelBuilder.Entity("laiscegonha.Models.MaeConsultaPreNatal", b =>
                {
                    b.Property<int>("IdMae");

                    b.Property<int>("IdConsultaPreNatal");

                    b.Property<int?>("ConsultaPreNatalId");

                    b.Property<int>("Id");

                    b.Property<int?>("MaeId");

                    b.HasKey("IdMae", "IdConsultaPreNatal");

                    b.HasIndex("ConsultaPreNatalId");

                    b.HasIndex("MaeId");

                    b.ToTable("MaeConsultaPreNatal");
                });

            modelBuilder.Entity("laiscegonha.Models.Parto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("DataParto");

                    b.Property<string>("Horario");

                    b.Property<int>("IdMae");

                    b.Property<string>("LocalNasci");

                    b.Property<int?>("MaeId");

                    b.HasKey("Id");

                    b.HasIndex("MaeId");

                    b.ToTable("Partos");
                });

            modelBuilder.Entity("laiscegonha.Models.Crianca", b =>
                {
                    b.HasOne("laiscegonha.Models.Mae", "Mae")
                        .WithMany("Crianca")
                        .HasForeignKey("MaeId");
                });

            modelBuilder.Entity("laiscegonha.Models.MaeConsultaPreNatal", b =>
                {
                    b.HasOne("laiscegonha.Models.ConsultaPreNatal", "ConsultaPreNatal")
                        .WithMany("MaeConsultaPreNatal")
                        .HasForeignKey("ConsultaPreNatalId");

                    b.HasOne("laiscegonha.Models.Mae", "Mae")
                        .WithMany("MaeConsultaPreNatal")
                        .HasForeignKey("MaeId");
                });

            modelBuilder.Entity("laiscegonha.Models.Parto", b =>
                {
                    b.HasOne("laiscegonha.Models.Mae", "Mae")
                        .WithMany("Parto")
                        .HasForeignKey("MaeId");
                });
#pragma warning restore 612, 618
        }
    }
}
